# TODO: 필요한 경우 수정하세요.

experiment_name: "KFood_MyModel_exp01"

dataset:
  name: "KFood"
  data_dir: "./data/kfood_dataset"
  batch_size: 64
  num_workers: 2

model:
  name: "MyModel"
  in_channels: 3

train:
  epochs: 30
  learning_rate: 0.001

